#!/bin/bash

# Apache and Shibd gets grumpy about PID files pre-existing from previous runs
echo "removing pid files"
rm -f /etc/httpd/run/httpd.pid /var/lock/subsys/shibd

# Make sure /etc/shibboleth/shibd-redhat is executable
echo "modifying exec for shibd-redhat"
chmod +x /etc/shibboleth/shibd-redhat

# Start Shibd
echo "starting shibd"
/etc/shibboleth/shibd-redhat start

# Start httpd
echo "starting httpd"
exec httpd -DFOREGROUND
